language: java
addons:
  sonarcloud:
    organization: "joseyustiz-github"
    token:
      secure: $SONAR_TOKEN
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner